In [2]:
pip install dice_ml

Collecting dice_ml
  Downloading dice_ml-0.9-py3-none-any.whl (2.6 MB)
                                              0.0/2.6 MB ? eta -:--:--
     --                                       0.2/2.6 MB 3.5 MB/s eta 0:00:01
     -------                                  0.5/2.6 MB 6.2 MB/s eta 0:00:01
     ----------                               0.7/2.6 MB 5.2 MB/s eta 0:00:01
     ------------                             0.8/2.6 MB 4.2 MB/s eta 0:00:01
     --------------                           0.9/2.6 MB 4.2 MB/s eta 0:00:01
     ---------------                          1.0/2.6 MB 3.8 MB/s eta 0:00:01
     ---------------                          1.0/2.6 MB 3.8 MB/s eta 0:00:01
     ---------------                          1.0/2.6 MB 3.8 MB/s eta 0:00:01
     ---------------                          1.0/2.6 MB 3.8 MB/s eta 0:00:01
     ---------------                          1.0/2.6 MB 3.8 MB/s eta 0:00:01
     ---------------                          1.0/2.6 MB 3.8 MB/s eta 0:00:01
     ---------------                          1.0/2.6 MB 3.8 MB/s eta 0:00:01
     -------------------------                1.6/2.6 MB 2.7 MB/s eta 0:00:01
     --------------------------------         2.1/2.6 MB 3.2 MB/s eta 0:00:01
     ----------------------------------       2.2/2.6 MB 3.2 MB/s eta 0:00:01
     ------------------------------------     2.3/2.6 MB 3.1 MB/s eta 0:00:01
     --------------------------------------   2.5/2.6 MB 3.1 MB/s eta 0:00:01
     ---------------------------------------  2.5/2.6 MB 3.1 MB/s eta 0:00:01
     ---------------------------------------- 2.6/2.6 MB 3.0 MB/s eta 0:00:00
Requirement already satisfied: jsonschema in c:\users\ayesha.amjad\appdata\local\anaconda3\lib\site-packages (from dice_ml) (4.17.3)
Requirement already satisfied: numpy in c:\users\ayesha.amjad\appdata\local\anaconda3\lib\site-packages (from dice_ml) (1.23.5)
Requirement already satisfied: pandas in c:\users\ayesha.amjad\appdata\local\anaconda3\lib\site-packages (from dice_ml) (1.5.3)
Requirement already satisfied: scikit-learn in c:\users\ayesha.amjad\appdata\roaming\python\python310\site-packages (from dice_ml) (1.2.2)
Requirement already satisfied: h5py in c:\users\ayesha.amjad\appdata\local\anaconda3\lib\site-packages (from dice_ml) (3.7.0)
Requirement already satisfied: tqdm in c:\users\ayesha.amjad\appdata\local\anaconda3\lib\site-packages (from dice_ml) (4.64.1)
Requirement already satisfied: attrs>=17.4.0 in c:\users\ayesha.amjad\appdata\local\anaconda3\lib\site-packages (from jsonschema->dice_ml) (22.1.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in c:\users\ayesha.amjad\appdata\local\anaconda3\lib\site-packages (from jsonschema->dice_ml) (0.18.0)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\ayesha.amjad\appdata\local\anaconda3\lib\site-packages (from pandas->dice_ml) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\ayesha.amjad\appdata\local\anaconda3\lib\site-packages (from pandas->dice_ml) (2022.7)
Requirement already satisfied: scipy>=1.3.2 in c:\users\ayesha.amjad\appdata\local\anaconda3\lib\site-packages (from scikit-learn->dice_ml) (1.10.0)
Requirement already satisfied: joblib>=1.1.1 in c:\users\ayesha.amjad\appdata\local\anaconda3\lib\site-packages (from scikit-learn->dice_ml) (1.1.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\ayesha.amjad\appdata\local\anaconda3\lib\site-packages (from scikit-learn->dice_ml) (2.2.0)
Requirement already satisfied: colorama in c:\users\ayesha.amjad\appdata\local\anaconda3\lib\site-packages (from tqdm->dice_ml) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\users\ayesha.amjad\appdata\local\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas->dice_ml) (1.16.0)
Installing collected packages: dice_ml
Successfully installed dice_ml-0.9
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import dice_ml
import numpy as np
import json
from catboost import CatBoostClassifier
from sklearn.metrics import f1_score, roc_auc_score, accuracy_score

In [4]:
import sys
sys.path.append("../")
import pandas as pd
from utils.data_utils import DataLoader

In [5]:
with open('C:/Users/ayesha.amjad/Documents/GitHub/MSDS-ML-Project/ML1-XAI/Project/models/CatBoost/best_param_enc2.json', 'r') as file:
    best_params = json.load(file)

In [6]:
data_loader = DataLoader(file_path='../data/raw/Churn_Modelling.xls' , target_column='Exited', test_size=0.2, random_state=42, clean_data=True)

In [13]:
df = data_loader.encoded_data
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9867 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Geography_France   9867 non-null   float64
 1   Geography_Germany  9867 non-null   float64
 2   Geography_Spain    9867 non-null   float64
 3   Gender_Female      9867 non-null   float64
 4   Gender_Male        9867 non-null   float64
 5   CreditScore        9867 non-null   int64
 6   Age                9867 non-null   int64
 7   Tenure             9867 non-null   int64
 8   Balance            9867 non-null   float64
 9   NumOfProducts      9867 non-null   int64
 10  HasCrCard          9867 non-null   int64
 11  IsActiveMember     9867 non-null   int64
 12  EstimatedSalary    9867 non-null   float64
dtypes: float64(7), int64(6)
memory usage: 1.1 MB

In [10]:
X_train, y_train = data_loader.get_train_data_enc()
X_test, y_test = data_loader.get_test_data_enc()
#y_train

In [11]:
model = CatBoostClassifier(**best_params)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(f"F1 Score {f1_score(y_test, y_pred, average='macro')}")
print(f"Accuracy {accuracy_score(y_test, y_pred)}")
print(f"ROC_AUC {roc_auc_score(y_test, y_pred)}")

0:	learn: 0.6404415	total: 147ms	remaining: 28.6s
1:	learn: 0.5966680	total: 152ms	remaining: 14.7s
2:	learn: 0.5587600	total: 155ms	remaining: 9.99s
3:	learn: 0.5270876	total: 158ms	remaining: 7.6s
4:	learn: 0.5020521	total: 161ms	remaining: 6.14s
5:	learn: 0.4788427	total: 164ms	remaining: 5.18s
6:	learn: 0.4591762	total: 168ms	remaining: 4.53s
7:	learn: 0.4424766	total: 171ms	remaining: 4.03s
8:	learn: 0.4277170	total: 175ms	remaining: 3.63s
9:	learn: 0.4153984	total: 178ms	remaining: 3.31s
10:	learn: 0.4049523	total: 181ms	remaining: 3.05s
11:	learn: 0.3953276	total: 185ms	remaining: 2.84s
12:	learn: 0.3868635	total: 189ms	remaining: 2.66s
13:	learn: 0.3786637	total: 193ms	remaining: 2.5s
14:	learn: 0.3720465	total: 196ms	remaining: 2.36s
15:	learn: 0.3665540	total: 202ms	remaining: 2.27s
16:	learn: 0.3616718	total: 205ms	remaining: 2.16s
17:	learn: 0.3575170	total: 208ms	remaining: 2.06s
18:	learn: 0.3536309	total: 212ms	remaining: 1.97s
19:	learn: 0.3503110	total: 215ms	remaining: 1.89s
20:	learn: 0.3465641	total: 219ms	remaining: 1.82s
21:	learn: 0.3432541	total: 222ms	remaining: 1.76s
22:	learn: 0.3408470	total: 226ms	remaining: 1.7s
23:	learn: 0.3388627	total: 229ms	remaining: 1.64s
24:	learn: 0.3361465	total: 233ms	remaining: 1.6s
25:	learn: 0.3340303	total: 237ms	remaining: 1.55s
26:	learn: 0.3319712	total: 240ms	remaining: 1.5s
27:	learn: 0.3299501	total: 243ms	remaining: 1.46s
28:	learn: 0.3283639	total: 247ms	remaining: 1.42s
29:	learn: 0.3271110	total: 251ms	remaining: 1.39s
30:	learn: 0.3258557	total: 254ms	remaining: 1.35s
31:	learn: 0.3238898	total: 258ms	remaining: 1.32s
32:	learn: 0.3227398	total: 262ms	remaining: 1.29s
33:	learn: 0.3218365	total: 266ms	remaining: 1.27s
34:	learn: 0.3202607	total: 269ms	remaining: 1.24s
35:	learn: 0.3191510	total: 274ms	remaining: 1.22s
36:	learn: 0.3177855	total: 278ms	remaining: 1.19s
37:	learn: 0.3166044	total: 281ms	remaining: 1.17s
38:	learn: 0.3159109	total: 285ms	remaining: 1.15s
39:	learn: 0.3149700	total: 289ms	remaining: 1.13s
40:	learn: 0.3140173	total: 292ms	remaining: 1.1s
41:	learn: 0.3133997	total: 296ms	remaining: 1.08s
42:	learn: 0.3125485	total: 299ms	remaining: 1.06s
43:	learn: 0.3119253	total: 302ms	remaining: 1.04s
44:	learn: 0.3112096	total: 306ms	remaining: 1.03s
45:	learn: 0.3106111	total: 309ms	remaining: 1.01s
46:	learn: 0.3098305	total: 313ms	remaining: 992ms
47:	learn: 0.3088106	total: 316ms	remaining: 975ms
48:	learn: 0.3084070	total: 320ms	remaining: 959ms
49:	learn: 0.3077332	total: 323ms	remaining: 944ms
50:	learn: 0.3069002	total: 327ms	remaining: 929ms
51:	learn: 0.3062803	total: 330ms	remaining: 915ms
52:	learn: 0.3055184	total: 334ms	remaining: 901ms
53:	learn: 0.3050242	total: 337ms	remaining: 887ms
54:	learn: 0.3042188	total: 340ms	remaining: 873ms
55:	learn: 0.3033118	total: 344ms	remaining: 861ms
56:	learn: 0.3027668	total: 348ms	remaining: 849ms
57:	learn: 0.3023819	total: 352ms	remaining: 837ms
58:	learn: 0.3016268	total: 356ms	remaining: 826ms
59:	learn: 0.3010292	total: 360ms	remaining: 816ms
60:	learn: 0.3005032	total: 364ms	remaining: 805ms
61:	learn: 0.2996841	total: 368ms	remaining: 796ms
62:	learn: 0.2990794	total: 373ms	remaining: 787ms
63:	learn: 0.2985244	total: 377ms	remaining: 778ms
64:	learn: 0.2977339	total: 382ms	remaining: 769ms
65:	learn: 0.2970011	total: 385ms	remaining: 759ms
66:	learn: 0.2965529	total: 391ms	remaining: 754ms
67:	learn: 0.2960906	total: 395ms	remaining: 744ms
68:	learn: 0.2955500	total: 399ms	remaining: 735ms
69:	learn: 0.2949369	total: 403ms	remaining: 726ms
70:	learn: 0.2944738	total: 408ms	remaining: 718ms
71:	learn: 0.2939829	total: 412ms	remaining: 709ms
72:	learn: 0.2934436	total: 416ms	remaining: 701ms
73:	learn: 0.2927195	total: 421ms	remaining: 695ms
74:	learn: 0.2923899	total: 427ms	remaining: 689ms
75:	learn: 0.2917203	total: 433ms	remaining: 683ms
76:	learn: 0.2911175	total: 439ms	remaining: 678ms
77:	learn: 0.2905809	total: 444ms	remaining: 671ms
78:	learn: 0.2901987	total: 448ms	remaining: 663ms
79:	learn: 0.2894669	total: 453ms	remaining: 656ms
80:	learn: 0.2889649	total: 457ms	remaining: 649ms
81:	learn: 0.2883985	total: 461ms	remaining: 641ms
82:	learn: 0.2878869	total: 465ms	remaining: 633ms
83:	learn: 0.2872020	total: 470ms	remaining: 627ms
84:	learn: 0.2866570	total: 474ms	remaining: 619ms
85:	learn: 0.2861756	total: 478ms	remaining: 611ms
86:	learn: 0.2857689	total: 482ms	remaining: 604ms
87:	learn: 0.2853503	total: 487ms	remaining: 597ms
88:	learn: 0.2850669	total: 491ms	remaining: 590ms
89:	learn: 0.2845932	total: 495ms	remaining: 583ms
90:	learn: 0.2841601	total: 500ms	remaining: 577ms
91:	learn: 0.2836702	total: 505ms	remaining: 571ms
92:	learn: 0.2830775	total: 509ms	remaining: 563ms
93:	learn: 0.2824889	total: 513ms	remaining: 557ms
94:	learn: 0.2817464	total: 518ms	remaining: 550ms
95:	learn: 0.2811284	total: 521ms	remaining: 543ms
96:	learn: 0.2807139	total: 525ms	remaining: 536ms
97:	learn: 0.2803241	total: 531ms	remaining: 531ms
98:	learn: 0.2798945	total: 535ms	remaining: 524ms
99:	learn: 0.2795860	total: 539ms	remaining: 518ms
100:	learn: 0.2789565	total: 546ms	remaining: 513ms
101:	learn: 0.2782992	total: 550ms	remaining: 507ms
102:	learn: 0.2777670	total: 554ms	remaining: 500ms
103:	learn: 0.2773499	total: 559ms	remaining: 494ms
104:	learn: 0.2770588	total: 565ms	remaining: 490ms
105:	learn: 0.2763391	total: 570ms	remaining: 484ms
106:	learn: 0.2759294	total: 577ms	remaining: 480ms
107:	learn: 0.2754010	total: 582ms	remaining: 474ms
108:	learn: 0.2749205	total: 588ms	remaining: 469ms
109:	learn: 0.2746910	total: 597ms	remaining: 467ms
110:	learn: 0.2742723	total: 603ms	remaining: 462ms
111:	learn: 0.2738710	total: 609ms	remaining: 457ms
112:	learn: 0.2734543	total: 615ms	remaining: 452ms
113:	learn: 0.2728515	total: 620ms	remaining: 446ms
114:	learn: 0.2723964	total: 629ms	remaining: 443ms
115:	learn: 0.2719754	total: 634ms	remaining: 438ms
116:	learn: 0.2716452	total: 640ms	remaining: 432ms
117:	learn: 0.2711606	total: 646ms	remaining: 427ms
118:	learn: 0.2707562	total: 651ms	remaining: 421ms
119:	learn: 0.2704524	total: 658ms	remaining: 417ms
120:	learn: 0.2701588	total: 663ms	remaining: 411ms
121:	learn: 0.2698516	total: 668ms	remaining: 405ms
122:	learn: 0.2693590	total: 674ms	remaining: 400ms
123:	learn: 0.2689299	total: 679ms	remaining: 394ms
124:	learn: 0.2685607	total: 685ms	remaining: 389ms
125:	learn: 0.2682171	total: 710ms	remaining: 394ms
126:	learn: 0.2677427	total: 716ms	remaining: 389ms
127:	learn: 0.2673046	total: 724ms	remaining: 385ms
128:	learn: 0.2670026	total: 729ms	remaining: 379ms
129:	learn: 0.2667030	total: 739ms	remaining: 375ms
130:	learn: 0.2661951	total: 745ms	remaining: 370ms
131:	learn: 0.2657740	total: 754ms	remaining: 366ms
132:	learn: 0.2654008	total: 760ms	remaining: 360ms
133:	learn: 0.2651164	total: 766ms	remaining: 354ms
134:	learn: 0.2647431	total: 772ms	remaining: 349ms
135:	learn: 0.2644352	total: 778ms	remaining: 343ms
136:	learn: 0.2640216	total: 785ms	remaining: 338ms
137:	learn: 0.2633718	total: 790ms	remaining: 332ms
138:	learn: 0.2629603	total: 796ms	remaining: 326ms
139:	learn: 0.2623991	total: 804ms	remaining: 322ms
140:	learn: 0.2620101	total: 809ms	remaining: 316ms
141:	learn: 0.2616900	total: 816ms	remaining: 310ms
142:	learn: 0.2613575	total: 822ms	remaining: 305ms
143:	learn: 0.2607353	total: 827ms	remaining: 299ms
144:	learn: 0.2600053	total: 834ms	remaining: 294ms
145:	learn: 0.2596368	total: 841ms	remaining: 288ms
146:	learn: 0.2592244	total: 850ms	remaining: 283ms
147:	learn: 0.2588889	total: 855ms	remaining: 277ms
148:	learn: 0.2586630	total: 862ms	remaining: 272ms
149:	learn: 0.2582621	total: 868ms	remaining: 266ms
150:	learn: 0.2580106	total: 873ms	remaining: 260ms
151:	learn: 0.2575695	total: 879ms	remaining: 254ms
152:	learn: 0.2570446	total: 883ms	remaining: 248ms
153:	learn: 0.2563796	total: 888ms	remaining: 242ms
154:	learn: 0.2555705	total: 895ms	remaining: 237ms
155:	learn: 0.2550934	total: 900ms	remaining: 231ms
156:	learn: 0.2547688	total: 905ms	remaining: 225ms
157:	learn: 0.2544955	total: 912ms	remaining: 219ms
158:	learn: 0.2542572	total: 918ms	remaining: 214ms
159:	learn: 0.2539424	total: 925ms	remaining: 208ms
160:	learn: 0.2536683	total: 930ms	remaining: 202ms
161:	learn: 0.2531463	total: 935ms	remaining: 196ms
162:	learn: 0.2525119	total: 941ms	remaining: 190ms
163:	learn: 0.2520607	total: 947ms	remaining: 185ms
164:	learn: 0.2516949	total: 952ms	remaining: 179ms
165:	learn: 0.2512162	total: 959ms	remaining: 173ms
166:	learn: 0.2509141	total: 965ms	remaining: 168ms
167:	learn: 0.2506178	total: 971ms	remaining: 162ms
168:	learn: 0.2502792	total: 977ms	remaining: 156ms
169:	learn: 0.2499102	total: 982ms	remaining: 150ms
170:	learn: 0.2496571	total: 988ms	remaining: 144ms
171:	learn: 0.2493476	total: 993ms	remaining: 139ms
172:	learn: 0.2490699	total: 998ms	remaining: 133ms
173:	learn: 0.2487594	total: 1s	remaining: 127ms
174:	learn: 0.2485904	total: 1.01s	remaining: 121ms
175:	learn: 0.2482783	total: 1.01s	remaining: 115ms
176:	learn: 0.2479107	total: 1.02s	remaining: 109ms
177:	learn: 0.2476268	total: 1.02s	remaining: 104ms
178:	learn: 0.2473051	total: 1.03s	remaining: 97.8ms
179:	learn: 0.2468803	total: 1.04s	remaining: 92.3ms
180:	learn: 0.2462307	total: 1.04s	remaining: 86.6ms
181:	learn: 0.2460036	total: 1.05s	remaining: 81.1ms
182:	learn: 0.2457506	total: 1.06s	remaining: 75.4ms
183:	learn: 0.2454742	total: 1.07s	remaining: 70ms
184:	learn: 0.2451715	total: 1.08s	remaining: 64.2ms
185:	learn: 0.2447680	total: 1.09s	remaining: 58.6ms
186:	learn: 0.2440759	total: 1.1s	remaining: 53ms
187:	learn: 0.2437597	total: 1.11s	remaining: 47.2ms
188:	learn: 0.2433099	total: 1.12s	remaining: 41.5ms
189:	learn: 0.2429883	total: 1.13s	remaining: 35.7ms
190:	learn: 0.2426172	total: 1.14s	remaining: 29.7ms
191:	learn: 0.2424527	total: 1.15s	remaining: 23.9ms
192:	learn: 0.2420441	total: 1.16s	remaining: 18ms
193:	learn: 0.2418321	total: 1.17s	remaining: 12ms
194:	learn: 0.2414405	total: 1.18s	remaining: 6.06ms
195:	learn: 0.2410666	total: 1.19s	remaining: 0us
F1 Score 0.7607704995064539
Accuracy 0.8637284701114488
ROC_AUC 0.731097892028421

In [44]:
Concat_df = pd.concat([X_train, y_train], axis=1)
Concat_df

,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
2496,1.0,0.0,0.0,1.0,0.0,567,45,4,0.00,2,0,1,121053.19,0
726,1.0,0.0,0.0,0.0,1.0,580,37,9,0.00,2,0,1,77108.66,0
4268,1.0,0.0,0.0,0.0,1.0,753,46,8,0.00,3,1,0,90747.94,1
5927,0.0,1.0,0.0,1.0,0.0,577,43,3,127940.47,1,0,0,125140.72,1
9264,0.0,0.0,1.0,0.0,1.0,414,60,3,0.00,2,1,1,93844.82,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9842,0.0,0.0,1.0,0.0,1.0,638,30,9,136808.53,2,1,1,106642.97,0
749,0.0,1.0,0.0,0.0,1.0,460,46,4,127559.97,2,1,1,126952.50,0
574,0.0,0.0,1.0,0.0,1.0,848,40,3,110929.96,1,1,1,30876.84,0
3827,0.0,1.0,0.0,0.0,1.0,794,57,3,117056.46,1,1,0,93336.93,1
5459,0.0,0.0,1.0,1.0,0.0,530,36,7,0.00,2,1,0,80619.09,0

In [45]:
Concat_df['NumOfProducts'] = Concat_df['NumOfProducts'].astype(float)
Concat_df['IsActiveMember'] = Concat_df['IsActiveMember'].astype(float)

In [68]:
data_dice = dice_ml.Data(dataframe=Concat_df, 
                         # For perturbation strategy
                         continuous_features=['Age', 
                                              'NumOfProducts',
                                              'EstimatedSalary',
                                              'IsActiveMember'], 
                         outcome_name='Exited')
# Model
model_dice = dice_ml.Model(model=model, 
                        # There exist backends for tf, torch, ...
                        backend="sklearn")
explainer = dice_ml.Dice(data_dice, 
                         model_dice, 
                         # Random sampling, genetic algorithm, kd-tree,...
                         method="random")

In [69]:
# Generate CF based on the blackbox model
input_datapoint = X_test[0:1]
#input_datapoint['NumOfProducts'] = input_datapoint['NumOfProducts'].astype(float)
#input_datapoint['IsActiveMember'] = input_datapoint['IsActiveMember'].astype(float)

input_datapoint

,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
1490,0.0,0.0,1.0,1.0,0.0,797,31,8,0.0,2,1,0,117916.63

In [70]:
cf = explainer.generate_counterfactuals(input_datapoint, 
                                  total_CFs=4, 
                                  permitted_range=None,
                                  desired_class="opposite")
# Visualize it
cf.visualize_as_dataframe(show_only_changes=True)

100%|██████████| 1/1 [00:01<00:00,  1.22s/it]

Query instance (original outcome : 0)

,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,0.0,0.0,1.0,1.0,0.0,797,31,8,0.0,2.0,1,0.0,117916.632812,0

Diverse Counterfactual set (new outcome: 1.0)

,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,0.0,0.0,1.0,1.0,0.0,797.0,60.0,8.0,0.0,-,1.0,-,117917.0099999998,1
1,0.0,0.0,1.0,1.0,0.0,797.0,62.0,8.0,0.0,-,1.0,0.5,117917.0099999998,1
2,0.0,0.0,1.0,1.0,0.0,797.0,66.0,8.0,0.0,3.7,1.0,-,117917.0099999998,1
3,0.0,0.0,1.0,1.0,0.0,797.0,67.0,8.0,111543.26,-,1.0,-,117917.0099999998,1

In [71]:
features_to_vary=['Age', 
                  'NumOfProducts',
                  'EstimatedSalary',
                  'IsActiveMember']
permitted_range={'Age':[20,30],
                 'EstimatedSalary':[116000, 119000]}
# Now generating explanations using the new feature weights
cf = explainer.generate_counterfactuals(input_datapoint, 
                                  total_CFs=34, 
                                  desired_class="opposite",
                                  permitted_range=permitted_range,
                                  features_to_vary=features_to_vary)
# Visualize it
cf.visualize_as_dataframe(show_only_changes=True)

100%|██████████| 1/1 [16:28<00:00, 988.15s/it]

Query instance (original outcome : 0)

,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,0.0,0.0,1.0,1.0,0.0,797,31,8,0.0,2.0,1,0.0,117916.632812,0

Diverse Counterfactual set (new outcome: 1.0)

,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,0.0,0.0,1.0,1.0,0.0,797.0,-,8.0,0.0,3.8,1.0,-,117917.0099999998,1.0
1,0.0,0.0,1.0,1.0,0.0,797.0,-,8.0,0.0,4.1,1.0,-,117917.0099999998,1.0
2,0.0,0.0,1.0,1.0,0.0,797.0,-,8.0,0.0,3.8,1.0,-,116232.87999994762,1.0
3,0.0,0.0,1.0,1.0,0.0,797.0,-,8.0,0.0,3.6,1.0,1.0,117917.0099999998,1.0
4,0.0,0.0,1.0,1.0,0.0,797.0,27.0,8.0,0.0,4.0,1.0,-,117917.0099999998,1.0
5,0.0,0.0,1.0,1.0,0.0,797.0,-,8.0,0.0,3.9,1.0,-,116778.07999994761,1.0
6,0.0,0.0,1.0,1.0,0.0,797.0,23.0,8.0,0.0,3.6,1.0,-,117917.0099999998,1.0
7,0.0,0.0,1.0,1.0,0.0,797.0,-,8.0,0.0,3.6,1.0,-,118112.37000005238,1.0
8,0.0,0.0,1.0,1.0,0.0,797.0,-,8.0,0.0,3.9,1.0,-,118803.36000005239,1.0
9,0.0,0.0,1.0,1.0,0.0,797.0,-,8.0,0.0,4.0,1.0,-,116371.76999994762,1.0
10,0.0,0.0,1.0,1.0,0.0,797.0,-,8.0,0.0,3.9,1.0,0.9,117917.0099999998,1.0
11,0.0,0.0,1.0,1.0,0.0,797.0,-,8.0,0.0,4.1,1.0,0.7,117917.0099999998,1.0
12,0.0,0.0,1.0,1.0,0.0,797.0,-,8.0,0.0,4.0,1.0,-,117492.34999994762,1.0
13,0.0,0.0,1.0,1.0,0.0,797.0,-,8.0,0.0,3.6,1.0,-,117916.99000003983,1.0
14,0.0,0.0,1.0,1.0,0.0,797.0,-,8.0,0.0,4.1,1.0,-,116528.98999994762,1.0
15,0.0,0.0,1.0,1.0,0.0,797.0,-,8.0,0.0,3.8,1.0,-,118340.76000005238,1.0
16,0.0,0.0,1.0,1.0,0.0,797.0,-,8.0,0.0,3.7,1.0,0.2,117917.0099999998,1.0
17,0.0,0.0,1.0,1.0,0.0,797.0,-,8.0,0.0,3.9,1.0,-,117216.11999994761,1.0
18,0.0,0.0,1.0,1.0,0.0,797.0,27.0,8.0,0.0,3.8,1.0,-,117917.0099999998,1.0
19,0.0,0.0,1.0,1.0,0.0,797.0,-,8.0,0.0,3.9,1.0,0.5,117917.0099999998,1.0
20,0.0,0.0,1.0,1.0,0.0,797.0,-,8.0,0.0,3.9,1.0,0.7,117917.0099999998,1.0
21,0.0,0.0,1.0,1.0,0.0,797.0,-,8.0,0.0,3.8,1.0,-,117917.0099999998,1.0
22,0.0,0.0,1.0,1.0,0.0,797.0,-,8.0,0.0,4.1,1.0,-,117917.0099999998,1.0
23,0.0,0.0,1.0,1.0,0.0,797.0,-,8.0,0.0,3.9,1.0,-,116551.16999994761,1.0
24,0.0,0.0,1.0,1.0,0.0,797.0,-,8.0,0.0,3.7,1.0,-,117917.0099999998,1.0
25,0.0,0.0,1.0,1.0,0.0,797.0,-,8.0,0.0,4.0,1.0,-,116330.51999994762,1.0
26,0.0,0.0,1.0,1.0,0.0,797.0,-,8.0,0.0,3.6,1.0,0.2,117917.0099999998,1.0
27,0.0,0.0,1.0,1.0,0.0,797.0,-,8.0,0.0,3.7,1.0,0.7,117917.0099999998,1.0
28,0.0,0.0,1.0,1.0,0.0,797.0,-,8.0,0.0,3.9,1.0,-,118722.99000005239,1.0
29,0.0,0.0,1.0,1.0,0.0,797.0,-,8.0,0.0,3.8,1.0,-,118490.20000005238,1.0
30,0.0,0.0,1.0,1.0,0.0,797.0,-,8.0,0.0,4.0,1.0,-,117917.0099999998,1.0
31,0.0,0.0,1.0,1.0,0.0,797.0,-,8.0,0.0,3.8,1.0,-,118890.8200000524,1.0
32,0.0,0.0,1.0,1.0,0.0,797.0,24.0,8.0,0.0,3.8,1.0,-,117917.0099999998,1.0
33,0.0,0.0,1.0,1.0,0.0,797.0,-,8.0,0.0,3.7,1.0,-,117917.0099999998,1.0